service: learning-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1

functions:
  server:
    handler: server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'